
title: Ethnicity facts and figures style guide

# Build settings
markdown: kramdown

baseurl: "/style-guide"

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
